# Generated by Django 3.2 on 2021-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='number_of_vote',
            field=models.IntegerField(default=0),
        ),
    ]
