# Generated by Django 3.2.4 on 2021-07-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210710_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='poll.poll')),
            ],
        ),
    ]
