# Generated by Django 3.2.4 on 2021-07-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_pollcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollcode',
            name='code',
            field=models.CharField(max_length=60),
        ),
    ]
