# Generated by Django 3.2.4 on 2021-07-11 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_pollcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollcode',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='poll.poll'),
        ),
    ]
