# Generated by Django 3.2.4 on 2021-07-11 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_alter_pollcode_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollcode',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
    ]
