# Generated by Django 3.2.4 on 2021-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_alter_poll_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
